name: GitHub Actions Demo
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  pull_request_target:
    branches: 
      - 'main'
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - run : |
          echo "Job triggered by event ${{ github.event_name}}"
          echo "Job triggered from branch ${{ github.ref_name }}"
      - uses: actions/checkout@v3.3.0
      - run : ls ${{ github.action_path }}
      
